#' Load annotation file
#'
#' @description This function loads an annotation file included in the `MiDNE` package.
#'
#' @param annot_type A character string defining the annotation file to upload. Accepted values are: 
#' 'BRCA_sample' to upload the clinical information of BRCA samples used in this study, and 'gene_drug'
#' to upload the comprehensive annotation table of known genes and drugs. This latter is generated by consulting different databases,
#' such as COSMIC, HGNC, and DrugBank.
#' @return A dataframe containing the requested annotation data.
#' @examples
#' # Load BRCA sample annotation file
#' BRCA_sample_annot <- loadAnnot(annot_type = 'BRCA_sample')
#'
#' # Load gene-drug annotation table
#' gene_drug_annot <- loadAnnot(annot_type = 'gene_drug')
#' @export

loadAnnot <- function(annot_type = 'gene_drug') {
  # Define valid annotation types
  valid_types <- c('BRCA_sample', 'gene_drug')
  
  # Ensure annot_type is valid
  if (!(annot_type %in% valid_types)) {
    stop(sprintf(
      "The 'annot_type' parameter is invalid. Use one of the following values: %s",
      paste(valid_types, collapse = ", ")
    ))
  }
  
  # Load the appropriate annotation file
  if (annot_type == 'gene_drug') {
    annot_path <- base::system.file(
      "extdata", "annotation/all_genes_drugs_annotation.RDS", package = "MiDNE"
    )
    annot <- readRDS(file = annot_path)
  } else if (annot_type == 'BRCA_sample') {
    annot_path <- base::system.file(
      "extdata", "annotation/TCGA_BRCA_01_28_2016_ClinicalFirehose.tsi",
      package = "MiDNE"
    )
    if (!file.exists(annot_path) || annot_path == "") {
      stop("The specified file for 'BRCA_sample' could not be found. Check your installation.")
    }
    annot <- utils::read.delim(file = annot_path, sep = "\t", stringsAsFactors = FALSE)
  }
  
  return(annot)
}